export enum ServiceStatus {
  PENDING = "PENDING",
  CONFIRMATIONPENDING = "CONFIRMATIONPENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  RETURNED_TO_CUSTOMER = "RETURNED_TO_CUSTOMER",
  CANCELLED = "CANCELLED",
}
